"""
Gmail Email Sender
-------------------
A standalone script for sending personalized emails via Gmail SMTP to contacts
found by the Business Finder (business_finder.py).

FEATURES:
  - Reads CSVs generated by business_finder.py (any niche/industry/city)
  - Sends via Gmail SMTP (smtp.gmail.com:587 with TLS)
  - Customizable HTML & plain-text email templates with personalization variables
  - Dry-run / preview mode (no emails sent)
  - Resume support: tracks which contacts have been emailed (append-mode log)
  - Rate-limiting between sends to avoid spam flags
  - Handles both old-format (name,website,emails) and new-format CSVs

SETUP — GMAIL APP PASSWORD (REQUIRED):
  1. Go to https://myaccount.google.com/security
  2. Enable "2-Step Verification" if not already enabled
  3. Go to "App passwords" (search in Google Account settings)
  4. Select "Mail" and your device, then click "Generate"
  5. Copy the 16-character password — use THIS, NOT your regular Gmail password

USAGE:
    # Preview mode (shows what would be sent, no actual sending)
    python gmail_email_sender.py --preview businesses.csv

    # Send emails
    python gmail_email_sender.py --sender youremail@gmail.com \\
        --app-password "xxxx xxxx xxxx xxxx" \\
        businesses.csv

    # Send with custom subject/template (tailor to any niche)
    python gmail_email_sender.py --sender youremail@gmail.com \\
        --app-password "xxxx xxxx xxxx xxxx" \\
        --subject "Partnership Opportunity at {company}" \\
        --template my_template.html \\
        --limit 10 \\
        businesses.csv

    # Resume from where you left off (skips already-sent contacts)
    python gmail_email_sender.py --sender youremail@gmail.com \\
        --app-password "xxxx xxxx xxxx xxxx" \\
        --logfile sent_log.csv \\
        businesses.csv

NOTES / ETIQUETTE:
  - Gmail's sending limit is ~500 emails/day for personal accounts.
  - Use a DELIBERATE delay between sends (default 30-60 seconds) to avoid being
    flagged as spam.
  - Always personalise the subject line — use {company} and {name} variables.
  - Respect opt-out/unsubscribe requests.
  - Comply with GDPR (EU), CAN-SPAM (US), and local anti-spam laws.
  - This script sends via YOUR personal Gmail — be mindful of your reputation.
"""

# ─── Imports ─────────────────────────────────────────────────────────────────────
import os
import re
import csv
import sys

# Force UTF-8 output for Windows console (fixes UnicodeEncodeError with arrows/emojis)
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
import time
import json
import argparse
import random
import smtplib
import logging
import datetime
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.utils import formataddr, formatdate

# ─── Configuration ───────────────────────────────────────────────────────────────

# Default delay range (seconds) between sending emails.
# Randomised so it looks more natural than a fixed interval.
DEFAULT_DELAY_MIN = 30
DEFAULT_DELAY_MAX = 60

# Default CSV log file for tracking sent emails
DEFAULT_SENT_LOG = "sent_emails_log.csv"

# Default email subject template (can be overridden via --subject).
# Available variables: {company}, {name}, {title}, {email}, {website}
DEFAULT_SUBJECT = "Business opportunity for {company}"

# Default HTML email template (can be overridden via --template).
# Generic template that works for ANY niche/industry.
# Available variables: {company}, {name}, {title}, {email}, {website}, {sender_name}
DEFAULT_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      border-bottom: 2px solid #2563EB;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }
    .header h1 {
      color: #1E40AF;
      font-size: 22px;
      margin: 0;
    }
    .badge {
      display: inline-block;
      background: #FEF3C7;
      color: #92400E;
      font-weight: bold;
      font-size: 13px;
      padding: 4px 12px;
      border-radius: 20px;
      margin-bottom: 16px;
    }
    .pricing-box {
      background: #EFF6FF;
      border: 2px solid #2563EB;
      border-radius: 12px;
      padding: 20px 24px;
      margin: 20px 0;
      text-align: center;
    }
    .pricing-box .price {
      font-size: 36px;
      font-weight: 800;
      color: #1E40AF;
    }
    .pricing-box .sub {
      font-size: 14px;
      color: #6B7280;
      margin-top: 4px;
    }
    .checklist {
      margin: 16px 0;
      padding: 0;
      list-style: none;
    }
    .checklist li {
      padding: 6px 0 6px 28px;
      background: url('data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20stroke%3D%22%2316A34A%22%20stroke-width%3D%223%22%3E%3Cpolyline%20points%3D%2220%206%209%2017%204%2012%22%2F%3E%3C%2Fsvg%3E') left center no-repeat;
      background-size: 18px;
    }
    .content p {
      margin-bottom: 14px;
    }
    .testimonial {
      background: #F9FAFB;
      border-left: 4px solid #2563EB;
      padding: 12px 16px;
      margin: 16px 0;
      font-style: italic;
      color: #4B5563;
    }
    .cta-button {
      display: inline-block;
      background: #2563EB;
      color: #ffffff !important;
      font-weight: bold;
      font-size: 16px;
      padding: 14px 32px;
      border-radius: 8px;
      text-decoration: none;
      margin: 8px 0;
    }
    .cta-button:hover {
      background: #1D4ED8;
    }
    .signature {
      margin-top: 25px;
      padding-top: 15px;
      border-top: 1px solid #eee;
      font-size: 13px;
      color: #666;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Hi{name_part},</h1>
  </div>
  <div class="content">
    <div class="badge">✨ Exclusive Offer — One-Time Only</div>

    <p>I came across <strong>{company}</strong> and was impressed by what you do. I'm reaching out because I help businesses like yours get <strong>more clients and grow their revenue</strong> — without spending a fortune on ads or cold calling.</p>

    <p>I built a tool that automatically finds businesses in any niche or city, extracts their contact information, and lets you reach out to them with personalized emails — all in one place.</p>

    <div class="pricing-box">
      <div class="price">€147</div>
      <div class="sub">One-Time Payment • Lifetime Access • No Monthly Fees</div>
    </div>

    <p><strong>Here's what you get:</strong></p>
    <ul class="checklist">
      <li>Find businesses in ANY niche or city — fitness, real estate, healthcare, restaurants, tech, you name it.</li>
      <li>Extract verified emails, phone numbers, and contact names of decision-makers.</li>
      <li>Built-in email sender — send personalized emails to hundreds of leads with one command.</li>
      <li>Smart delay system so your emails land in inboxes, not spam folders.</li>
      <li>Works anywhere in the world — US, Europe, Middle East, Africa. No API keys needed.</li>
      <li>Lifetime access with all future updates included.</li>
    </ul>

    <div class="testimonial">
      "I found 80+ businesses with valid emails in under 30 minutes for a niche I was targeting. The automated email sender alone saved me days of manual work."
    </div>

    <p style="text-align: center; font-size: 16px; font-weight: bold;">
      <span class="cta-button">-> Reply to Get Instant Access</span>
    </p>

    <p style="font-size: 11px; color: #D1D5DB; text-align: center; margin-top: 20px;">
      If you'd rather not hear from me again, just reply with "unsubscribe" and I'll remove you instantly.
    </p>
  </div>
  <div class="signature">
    <p>Best regards,<br><strong>{sender_name}</strong></p>
  </div>
</body>
</html>"""

# Default plain-text fallback (used when no custom template is provided).
# Generic template that works for ANY niche/industry.
DEFAULT_TEXT_TEMPLATE = """\
Hi{name_part},

[Exclusive Offer - One-Time Only]

I came across {company} and was impressed by what you do. I'm reaching out because I help businesses like yours get more clients and grow their revenue -- without spending a fortune on ads or cold calling.

I built a tool that automatically finds businesses in any niche or city, extracts their contact information, and lets you reach out to them with personalized emails -- all in one place.

PRICE: 147 EUR -- One-Time Payment
Lifetime Access. No Monthly Fees. Ever.

Here's what you get:
- Find businesses in ANY niche or city -- fitness, real estate, healthcare, restaurants, tech, you name it.
- Extract verified emails, phone numbers, and contact names of decision-makers.
- Built-in email sender -- send personalized emails to hundreds of leads with one command.
- Smart delay system so your emails land in inboxes, not spam folders.
- Works anywhere in the world -- US, Europe, Middle East, Africa. No API keys needed.
- Lifetime access with all future updates included.

"I found 80+ businesses with valid emails in under 30 minutes for a niche I was targeting. The automated email sender alone saved me days of manual work."

Reply to this email to get instant access.

One payment. Lifetime updates. No recurring charges. Ever.

Best regards,
{sender_name}"""

# ─── Helpers ─────────────────────────────────────────────────────────────────────

# Terminal-safe symbols (Windows cp1252 compat)
_CHECK = "[OK]"
_CROSS = "[X]"
_WARN = "[!]"
_ARROW = "->"
_LINE = "-" * 60
_INFO = "[i]"

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("gmail_sender")


def load_csv(filepath: str) -> list[dict]:
    """
    Load a CSV file and return a list of rows as dicts.
    Handles both:
      - New format: Company Name, Website, WhatsApp Link, Phone Number,
        WhatsApp Source, Contact Person, Contact Title, Contact Email,
        Founder Source, All Emails Found
      - Old format: name, website, emails
    """
    rows = []
    with open(filepath, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        # Normalise header names
        fieldnames = [h.strip() for h in reader.fieldnames]
        reader.fieldnames = fieldnames

        for row in reader:
            # Strip whitespace from all values
            cleaned = {k.strip(): v.strip() if v else "" for k, v in row.items()}
            rows.append(cleaned)

    if not rows:
        logger.warning(f"CSV file '{filepath}' is empty or has no data rows.")
        return []

    # Detect format by looking at available columns
    first = rows[0]
    is_new_format = "Company Name" in first
    is_old_format = "name" in first

    if not is_new_format and not is_old_format:
        logger.warning(
            f"Unknown CSV format. Columns found: {list(first.keys())}"
        )
        logger.warning("Expected columns: 'Company Name' (new) or 'name' (old)")

    return rows


def get_contact_email(row: dict) -> str | None:
    """Extract the best email from a CSV row, regardless of format."""
    # New format: 'Contact Email' or 'All Emails Found'
    contact_email = row.get("Contact Email", "").strip()
    if contact_email and is_valid_target_email(contact_email):
        return contact_email

    # Fallback to 'All Emails Found' — take the first valid one
    all_emails = row.get("All Emails Found", "").strip()
    if all_emails:
        emails = [e.strip() for e in all_emails.split(";") if e.strip()]
        # Filter out junk emails (sentry, npm packages, etc.)
        valid = [e for e in emails if is_valid_target_email(e)]
        if valid:
            return valid[0]

    # Old format: 'emails' column
    emails_field = row.get("emails", "").strip()
    if emails_field:
        emails = [e.strip() for e in emails_field.split(";") if e.strip()]
        valid = [e for e in emails if is_valid_target_email(e)]
        if valid:
            return valid[0]

    return None


def is_valid_target_email(email: str) -> bool:
    """Check if an email is a valid target for sending (not junk/spam)."""
    email = email.strip().lower()

    # Must have @ and a proper domain
    if "@" not in email or "." not in email.split("@")[1]:
        return False

    # Reject obvious junk
    junk_patterns = [
        "sentry", "tracking", "analytics", "noreply", "no-reply",
        "mailer-daemon", "postmaster", "npm@", "lodash@", "react@",
        "core-js", "intl-segmenter", "focus-within", "rspack@",
        "slick-carousel", "whatwg-fetch", "webpack",
        "example.com", "domain.com", "yourdomain.com",
        "mijnwebsite.com", "provider.com",
        # Hex hash patterns (sentry-like)
        r'^[a-f0-9]{32}@',
        r'^[a-f0-9]{8,}@',
    ]
    for pat in junk_patterns:
        if re.search(pat, email, re.IGNORECASE):
            return False

    # Reject emails with version numbers (e.g., bundle@3.2.1)
    if re.search(r'@.*\d+\.\d+\.\d+', email):
        return False

    # Reject addresses with 'www.' in the domain (almost always scraped wrong)
    domain = email.split("@", 1)[1] if "@" in email else ""
    if ".www." in domain or domain.startswith("www."):
        return False
    # Reject non-ASCII characters in email (rarely valid for business SMTP)
    if not _can_encode_ascii(email):
        return False

    return True


def get_company_name(row: dict) -> str:
    """Extract company name from a CSV row."""
    return row.get("Company Name") or row.get("name") or "Unknown Company"


def get_contact_name(row: dict) -> str | None:
    """Extract contact person name from a CSV row."""
    return row.get("Contact Person") or row.get("contact_person") or None


def get_contact_title(row: dict) -> str | None:
    """Extract contact title from a CSV row."""
    return row.get("Contact Title") or row.get("contact_title") or None


def get_website(row: dict) -> str | None:
    """Extract website from a CSV row."""
    url = row.get("Website") or row.get("website") or None
    if url and not url.startswith("http"):
        url = "https://" + url
    return url


def load_template(filepath: str, fallback: str) -> str:
    """Load an HTML or text template from file, or return fallback."""
    if filepath and os.path.isfile(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        logger.info(f"Loaded template from '{filepath}' ({len(content)} chars)")
        return content
    return fallback


def render_template(template: str, variables: dict) -> str:
    """Render a template by replacing {variable} placeholders."""
    result = template
    for key, value in variables.items():
        placeholder = "{" + key + "}"
        result = result.replace(placeholder, str(value) if value else "")
    return result


def build_email(
    sender_email: str,
    sender_name: str,
    recipient_email: str,
    recipient_name: str | None,
    company: str,
    title: str | None,
    website: str | None,
    subject_template: str,
    html_template: str,
    text_template: str,
) -> tuple[str, str, str]:
    """
    Build a MIME email message with both HTML and plain-text alternatives.

    Returns (sender, recipient, message_string).
    """
    # Build subject
    subject_vars = {
        "company": company,
        "name": recipient_name or "there",
        "title": title or "",
        "email": recipient_email,
        "website": website or "",
    }
    subject = render_template(subject_template, subject_vars)

    # Build name part for greeting
    name_part = f" {recipient_name}" if recipient_name else ""

    # Template variables
    template_vars = {
        "company": company,
        "name": recipient_name or "",
        "title": title or "",
        "email": recipient_email,
        "website": website or "",
        "sender_name": sender_name,
        "name_part": name_part,
    }

    # Render HTML and text versions
    html_content = render_template(html_template, template_vars)
    text_content = render_template(text_template, template_vars)

    # Build MIME message
    msg = MIMEMultipart("alternative")
    msg["From"] = formataddr((sender_name, sender_email))
    msg["To"] = recipient_email
    msg["Subject"] = subject
    msg["Date"] = formatdate(localtime=True)
    msg["Message-ID"] = (
        f"<{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}."
        f"{random.randint(1000, 9999)}@{sender_email.split('@')[1]}>"
    )

    # Attach parts in order: plain-text first (preferred by some clients), then HTML
    msg.attach(MIMEText(text_content, "plain", "utf-8"))
    msg.attach(MIMEText(html_content, "html", "utf-8"))

    return sender_email, recipient_email, msg.as_string()


def _can_encode_ascii(text: str) -> bool:
    """Check if a string can be safely encoded as ASCII."""
    try:
        text.encode("ascii")
        return True
    except (UnicodeEncodeError, UnicodeDecodeError):
        return False


def send_email(
    smtp_conn: smtplib.SMTP,
    sender_email: str,
    recipient_email: str,
    message: str,
) -> bool:
    """Send a single email via an existing SMTP connection.
    Uses SMTPUTF8 for non-ASCII addresses when possible.
    """
    try:
        mail_options = []
        rcpt_options = []
        # If the recipient address has non-ASCII chars, use SMTPUTF8
        if not _can_encode_ascii(recipient_email):
            mail_options.append("SMTPUTF8")
            mail_options.append("BODY=8BITMIME")
        smtp_conn.sendmail(
            sender_email,
            [recipient_email],
            message,
            mail_options=mail_options,
            rcpt_options=rcpt_options,
        )
        return True
    except smtplib.SMTPException as e:
        logger.error(f"SMTP error sending to {recipient_email}: {e}")
        return False
    except UnicodeEncodeError as e:
        logger.error(f"Encoding error for {recipient_email}: {e}")
        return False


def load_sent_log(filepath: str) -> set:
    """Load the set of already-sent email addresses from the log CSV."""
    sent = set()
    if not os.path.isfile(filepath):
        return sent
    try:
        with open(filepath, "r", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                email = (row.get("Email") or row.get("Recipient Email") or "").strip().lower()
                if email:
                    sent.add(email)
    except (IOError, csv.Error) as e:
        logger.warning(f"Could not read sent log '{filepath}': {e}")
    return sent


def append_to_sent_log(filepath: str, row: dict):
    """Append one entry to the sent-email log CSV."""
    is_new = not os.path.isfile(filepath)
    fieldnames = [
        "Timestamp", "Company", "Contact Name", "Contact Title",
        "Recipient Email", "Website", "Status",
    ]
    try:
        with open(filepath, "a", newline="", encoding="utf-8-sig") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            if is_new:
                writer.writeheader()
            writer.writerow(row)
    except IOError as e:
        logger.warning(f"Could not write to sent log '{filepath}': {e}")


# ─── Main ────────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(
        description="Send personalized emails via Gmail SMTP to business contacts from any niche/industry.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "EXAMPLES:\n"
            "  # Preview mode -- show what would be sent (no actual sending)\n"
            "  python gmail_email_sender.py --preview businesses.csv\n\n"
            "  # Send to the first 5 businesses\n"
            "  python gmail_email_sender.py --sender me@gmail.com \\\n"
            "      --app-password \"xxxx xxxx xxxx xxxx\" --limit 5 businesses.csv\n\n"
            "  # Use a custom HTML template (tailor to your niche)\n"
            "  python gmail_email_sender.py --sender me@gmail.com \\\n"
            "      --app-password \"xxxx xxxx xxxx xxxx\" --template my_template.html \\\n"
            "      businesses.csv\n\n"
            "  # Resume: skip contacts already logged in sent_log.csv\n"
            "  python gmail_email_sender.py --sender me@gmail.com \\\n"
            "      --app-password \"xxxx xxxx xxxx xxxx\" --logfile sent_log.csv \\\n"
            "      businesses.csv\n"
        ),
    )

    parser.add_argument(
        "csv_file",
        help="Path to the CSV file containing business contacts (any niche/city)",
    )

    # Sender credentials
    parser.add_argument(
        "--sender", "-s",
        help="Your Gmail address (e.g., youraccount@gmail.com)",
        default=os.environ.get("GMAIL_SENDER", ""),
    )
    parser.add_argument(
        "--app-password", "-p",
        help="Gmail App Password (16 chars). Not your regular password! "
             "Can also be set via GMAIL_APP_PASSWORD env variable.",
        default=os.environ.get("GMAIL_APP_PASSWORD", ""),
    )
    parser.add_argument(
        "--sender-name",
        help="Your display name (default: the part before @ in your email)",
        default="",
    )

    # Email content
    parser.add_argument(
        "--subject",
        help=f"Email subject template (default: '{DEFAULT_SUBJECT}')",
        default=DEFAULT_SUBJECT,
    )
    parser.add_argument(
        "--template",
        help="Path to an HTML email template file. The file should use "
             "{company}, {name}, {title}, {sender_name} placeholders.",
        default="",
    )

    # Behaviour
    parser.add_argument(
        "--preview", "-n",
        action="store_true",
        help="Preview mode: show what would be sent, but don't actually send anything",
    )
    parser.add_argument(
        "--limit", "-l",
        type=int,
        default=0,
        help="Maximum number of emails to send (0 = unlimited)",
    )
    parser.add_argument(
        "--skip",
        type=int,
        default=0,
        help="Skip the first N valid contacts (useful for resuming without a log)",
    )
    parser.add_argument(
        "--delay-min",
        type=int,
        default=DEFAULT_DELAY_MIN,
        help=f"Minimum delay in seconds between sends (default: {DEFAULT_DELAY_MIN})",
    )
    parser.add_argument(
        "--delay-max",
        type=int,
        default=DEFAULT_DELAY_MAX,
        help=f"Maximum delay in seconds between sends (default: {DEFAULT_DELAY_MAX})",
    )
    parser.add_argument(
        "--logfile",
        help="Path to CSV log of sent emails (default: auto-generated "
             f"'{DEFAULT_SENT_LOG}' if not in preview mode)",
        default="",
    )
    parser.add_argument(
        "--min-email-length",
        type=int,
        default=6,
        help="Minimum length a valid email can be (default: 6). Raise this "
             "to be more strict.",
    )
    parser.add_argument(
        "--only-with-name",
        action="store_true",
        help="Only send to contacts that have a person's name (skip anonymous)",
    )
    parser.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="Suppress sending progress details (only show errors/summary)",
    )

    args = parser.parse_args()

    # Validate
    if not args.preview:
        if not args.sender:
            parser.error(
                "--sender is required (or set GMAIL_SENDER env variable). "
                "Use --preview to test without sending."
            )
        if not args.app_password:
            parser.error(
                "--app-password is required (or set GMAIL_APP_PASSWORD env variable). "
                "Use --preview to test without sending."
            )

    if args.delay_min < 1:
        parser.error("--delay-min must be at least 1 second.")
    if args.delay_max < args.delay_min:
        parser.error("--delay-max must be >= --delay-min.")

    if not args.sender_name:
        args.sender_name = args.sender.split("@")[0] if args.sender else "Sender"

    return args


def main():
    args = parse_args()

    sender_email = args.sender
    sender_name = args.sender_name
    csv_path = args.csv_file

    # Load the CSV
    if not os.path.isfile(csv_path):
        print(f"{_CROSS} File not found: {csv_path}")
        sys.exit(1)

    print(_LINE)
    print(f"  Gmail Email Sender")
    if args.preview:
        print(f"  Mode: PREVIEW (no emails will be sent)")
    print(f"  CSV: {csv_path}")
    print(f"  Sender: {sender_name} <{sender_email}>" if sender_email else "  Sender: (preview mode)")
    if args.limit > 0:
        print(f"  Limit: {args.limit} emails")
    print(_LINE)
    print()

    rows = load_csv(csv_path)
    if not rows:
        print(f"{_CROSS} No data found in CSV.")
        sys.exit(1)

    print(f"{_INFO} Loaded {len(rows)} row(s) from CSV.\n")

    # Filter rows to valid contacts
    contacts = []
    for row in rows:
        company = get_company_name(row)
        email = get_contact_email(row)

        if not email:
            continue
        if len(email) < args.min_email_length:
            continue

        contact_name = get_contact_name(row)
        contact_title = get_contact_title(row)
        website = get_website(row)

        contacts.append({
            "company": company,
            "email": email,
            "name": contact_name,
            "title": contact_title,
            "website": website,
            "raw_row": row,
        })

    if not contacts:
        print(f"{_CROSS} No valid email addresses found in CSV.")
        sys.exit(1)

    print(f"{_INFO} Found {len(contacts)} contact(s) with valid email addresses.")
    if args.only_with_name:
        contacts = [c for c in contacts if c["name"]]
        print(f"{_INFO} After filtering to named contacts: {len(contacts)}")

    # Apply skip
    if args.skip > 0:
        contacts = contacts[args.skip:]
        print(f"{_INFO} Skipped first {args.skip}. Remaining: {len(contacts)}")

    # Apply limit
    if args.limit > 0 and len(contacts) > args.limit:
        contacts = contacts[:args.limit]
        print(f"{_INFO} Limited to first {args.limit} contacts.")

    if not contacts:
        print(f"{_CROSS} No contacts to process.")
        sys.exit(1)

    # Load sent log (skip already-sent emails)
    sent_log_path = args.logfile or DEFAULT_SENT_LOG
    already_sent = set()
    if not args.preview and os.path.isfile(sent_log_path):
        already_sent = load_sent_log(sent_log_path)
        if already_sent:
            before = len(contacts)
            contacts = [c for c in contacts if c["email"].lower() not in already_sent]
            skipped_sent = before - len(contacts)
            if skipped_sent:
                print(f"{_INFO} Skipped {skipped_sent} already-sent contact(s) "
                      f"(from log: {sent_log_path})")

    if not contacts:
        print(f"{_CROSS} All contacts have already been sent to (according to log).")
        sys.exit(0)

    # Load templates
    html_template = load_template(args.template, DEFAULT_HTML_TEMPLATE)
    text_template = DEFAULT_TEXT_TEMPLATE

    # ── Preview Mode ──
    if args.preview:
        print(f"\n{'=' * 60}")
        print(f"  PREVIEW — {len(contacts)} email(s) ready to send")
        print(f"{'=' * 60}\n")

        for i, c in enumerate(contacts, 1):
            company = c["company"]
            email = c["email"]
            name = c["name"] or "(no name)"
            title = c["title"] or ""
            website = c["website"] or ""

            # Render subject
            subj_vars = {
                "company": company,
                "name": c["name"] or "there",
                "title": title,
                "email": email,
                "website": website,
            }
            subject = render_template(args.subject, subj_vars)

            print(f"  [{i}/{len(contacts)}]")
            print(f"    Company:  {company}")
            print(f"    To:       {email}")
            print(f"    Name:     {name}" + (f" ({title})" if title else ""))
            print(f"    Subject:  {subject}")
            print(f"    Website:  {website}")
            print()

        print(f"{_LINE}")
        print(f"  {_CHECK} Preview complete — {len(contacts)} email(s) ready.")
        total_delay = len(contacts) * ((args.delay_min + args.delay_max) / 2)
        print(f"  Estimated time to send: ~{total_delay / 60:.0f} minute(s)")
        print(f"  To send, run: python gmail_email_sender.py --sender YOUR_EMAIL"
              f" --app-password \"YOUR_APP_PW\" \"{csv_path}\"")
        print(f"{_LINE}")
        return

    # ── Real Send Mode ──
    print(f"\n{'=' * 60}")
    print(f"  SENDING — {len(contacts)} email(s)")
    print(f"  From: {sender_name} <{sender_email}>")
    print(f"  Delay: {args.delay_min}-{args.delay_max}s between sends")
    print(f"  Log:   {sent_log_path}")
    print(f"{'=' * 60}\n")

    # Connect to Gmail SMTP
    try:
        smtp = smtplib.SMTP("smtp.gmail.com", 587, timeout=30)
        smtp.ehlo()
        smtp.starttls()
        smtp.ehlo()
        smtp.login(sender_email, args.app_password)
        print(f"  {_CHECK} Connected to Gmail SMTP as {sender_email}\n")
    except smtplib.SMTPAuthenticationError:
        print(f"  {_CROSS} Authentication failed. Make sure you:\n"
              f"         1. Have 2-Step Verification enabled on your Google account\n"
              f"         2. Created an App Password (not your regular password)\n"
              f"         3. Are using the correct 16-character App Password")
        sys.exit(1)
    except (smtplib.SMTPException, OSError) as e:
        print(f"  {_CROSS} Could not connect to Gmail SMTP: {e}")
        sys.exit(1)

    # Send emails
    sent_count = 0
    error_count = 0
    start_time = time.time()
    total = len(contacts)

    for idx, c in enumerate(contacts, 1):
        company = c["company"]
        email = c["email"]
        name = c["name"]
        title = c["title"]
        website = c["website"]

        # Build the email
        try:
            _, _, msg_string = build_email(
                sender_email=sender_email,
                sender_name=sender_name,
                recipient_email=email,
                recipient_name=name,
                company=company,
                title=title,
                website=website,
                subject_template=args.subject,
                html_template=html_template,
                text_template=text_template,
            )
        except Exception as e:
            logger.error(f"Error building email for {company} ({email}): {e}")
            error_count += 1
            continue

        # Send
        success = send_email(smtp, sender_email, email, msg_string)

        if success:
            sent_count += 1
            if not args.quiet:
                name_display = f" ({name})" if name else ""
                print(f"  [{idx}/{total}] {_CHECK} Sent -> {company}{name_display} <{email}>")

            # Log the send
            log_row = {
                "Timestamp": datetime.datetime.now().isoformat(),
                "Company": company,
                "Contact Name": name or "",
                "Contact Title": title or "",
                "Recipient Email": email,
                "Website": website or "",
                "Status": "sent",
            }
            append_to_sent_log(sent_log_path, log_row)
        else:
            error_count += 1
            print(f"  [{idx}/{total}] {_CROSS} Failed → {company} <{email}>")

        # Delay between sends (skip after last)
        if idx < total:
            delay = random.randint(args.delay_min, args.delay_max)
            if not args.quiet:
                print(f"         Waiting {delay}s...")
            time.sleep(delay)

    # Done
    smtp.quit()

    elapsed = time.time() - start_time
    print()
    print(_LINE)
    print(f"  {_CHECK} Sending complete!")
    print(f"  Sent:   {sent_count}")
    if error_count:
        print(f"  Errors: {error_count}")
    print(f"  Time:   {elapsed / 60:.1f} minute(s)")
    print(f"  Log:    {sent_log_path}")
    print(_LINE)

    if sent_count > 0:
        print(f"\n  {_INFO} To resume later, use --logfile {sent_log_path} to skip already-sent contacts.")
    print()


if __name__ == "__main__":
    main()
